name: Allons-y!

on:
  pull_request:
    branches: ["main"]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup up Java
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean install

      - name: Caching dependencies from Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn test

      - name: Generate JavaDoc with Maven
        run: mvn javadoc:javadoc

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./target/site/apidocs"

