name: GoogleStyle-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3A
        with:
          args: "--replace --skip-reflowing-long-strings"
          skip-commit: false
          commit-message: "style: Apply `Google Syle` formatting."
